import { ArrowUpRight, Download, Link as LinkIcon, Mail } from "lucide-react";
import { SiteHeader } from "@/components/site-shell";
import { BuildCredit } from "@/components/build-credit";

export const metadata = { title: "About" };
const resume="https://drive.google.com/file/d/1217wGnPp_2ZPg1xSuei8SWV_cGzKsZ8V/view?usp=sharing";

export default function AboutPage(){
 return <main><SiteHeader emailLocation="about_header"/>
  <section className="page-hero about-hero wrap"><p className="section-index">ABOUT / ERIN KIM</p><h1>Business context.<br/>Useful answers.</h1><p>I’m a data analytics intern building reporting experiences that help people understand what is happening, why it matters, and what to do next.</p></section>
  <section className="about-command wrap"><aside><figure className="portrait-mark about-photo"><img src="/images/erin-professional.webp" alt="Erin Kim"/><span>ERIN KIM<br/>DATA ANALYTICS</span><i>01</i></figure><div className="mini-facts"><div><small>BASED IN</small><b>Georgia</b></div><div><small>STUDYING</small><b>Online B.B.A. MIS</b></div><div><small>STATUS</small><b>Available now</b></div></div></aside><div className="about-narrative"><p className="section-index">01 / PROFESSIONAL NARRATIVE</p><h2>I found my way into analytics through the questions behind the work.</h2><p>While working in marketing, I became increasingly drawn to the reporting behind each campaign and process. I wanted to know why performance changed, where time was being lost, and how the information could be organized so the team could use it more easily. Building reports and improving workflows became the part of the work I kept wanting to explore.</p><p>Moving into a data analytics role gave me the chance to spend more time on the work I had already been gravitating toward. These days, I spend most of my time building dashboards in Power BI and DataRails, with plenty of Excel in the mix. My marketing experience also means I pay close attention to how a report reads. If someone has to dig around to understand what it is telling them, I know it still needs work.</p></div></section>
  <section className="about-systems wrap"><div className="systems-head"><p className="section-index">02 / CORE COMPETENCIES</p><h2>How I approach the work.</h2></div><div className="systems-grid"><article><span>01</span><small>REPORTING &amp; KPI DESIGN</small><h3>Clear measures for real questions.</h3><p>Dashboard UX, KPI development, data visualization, executive reporting, and reporting structures designed around the decision at hand.</p></article><article><span>02</span><small>PROCESS &amp; WORKFLOW ANALYSIS</small><h3>Better systems behind the answer.</h3><p>Data cleaning, data modeling, workflow mapping, process improvement, and reporting automation that create a reliable foundation for the finished report.</p></article><article><span>03</span><small>MARKETING &amp; BUSINESS CONTEXT</small><h3>Context people can use.</h3><p>Marketing analytics, data storytelling, technical writing, cross-functional collaboration, and translating business questions into clear reporting requirements.</p></article></div></section>
  <section className="about-learning wrap"><div className="learning-heading"><p className="section-index">03 / CONTINUOUS LEARNING</p><h2>Learning while building.</h2><p>My education and professional experience run in parallel, supported by verified training in analytics and Excel.</p></div><div className="learning-grid"><article><span>IN PROGRESS</span><h3>B.B.A. in Management Information Systems</h3><p>Business Analytics concentration at Columbus State University, completed fully online so I can continue prioritizing professional experience.</p></article><a href="https://skillshop.credential.net/d8b48313-71f3-4d4b-b1bd-7e034e2b339d" target="_blank" rel="noreferrer"><span>CERTIFIED</span><h3>Google Analytics Certification</h3><p>Google Skillshop · Issued December 2025 · Active through December 2026</p><b>VIEW CREDENTIAL <ArrowUpRight size={15}/></b></a><a href="https://certificates.simnetonline.com/78b6197e-b48e-4ec7-a4fa-423a73da150d" target="_blank" rel="noreferrer"><span>CERTIFIED</span><h3>Essential Skills in Microsoft Excel</h3><p>McGraw Hill · Issued September 2026</p><b>VIEW CREDENTIAL <ArrowUpRight size={15}/></b></a></div></section>
  <section className="about-personality wrap"><div><p className="section-index">04 / OFF THE CLOCK</p><h2>The curiosity<br/>keeps running.</h2></div><figure className="personality-photo"><img src="/images/erin-f1.webp" alt="Erin at an Oracle Red Bull Racing event"/></figure><div><p>Outside of work, I’m usually following Formula 1, building a dashboard for fun, or adding another LEGO set or Smiski to the collection. I also take family game nights seriously enough to track an entire F1 Monopoly season.</p><div className="interest-cloud"><span>Formula 1</span><span>Dashboard experiments</span><span>LEGO</span></div></div></section>
  <section className="about-cta"><div className="wrap"><div><p className="section-index">05 / CONNECT</p><h2>Let’s put the data to work.</h2><p>I’m available now and completing my bachelor’s remotely so I can continue prioritizing professional experience.</p></div><div className="about-actions"><a href="mailto:eokim002@gmail.com" data-ga-event="email_click" data-ga-location="about_connect"><Mail size={17}/> Email <ArrowUpRight size={16}/></a><a href="https://www.linkedin.com/in/eokim002/" target="_blank" rel="noreferrer" data-ga-event="linkedin_click" data-ga-location="about_connect"><LinkIcon size={17}/> LinkedIn <ArrowUpRight size={16}/></a><a href={resume} target="_blank" rel="noreferrer" data-ga-event="resume_click" data-ga-location="about_connect"><Download size={17}/> Resume <ArrowUpRight size={16}/></a></div></div></section><BuildCredit/>
  </main>
}
