"use client";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { useState } from "react";
import { trackEvent } from "@/components/analytics";
const items=[
 {slug:"pe-license-coverage-dashboard",n:"01",type:"Analytics & BI",title:"PE License Coverage Dashboard",summary:"An interactive view of license status, renewal timing, and geographic coverage across hundreds of records.",tools:"Power BI · Data Modeling · Data Cleaning",tone:"blue",image:"/images/pe-license-coverage-dashboard.png",alt:"Power BI dashboard showing randomized professional engineering license data",featured:true},
 {slug:"digital-marketing-dashboard",n:"02",type:"Analytics & BI",title:"Digital Marketing Performance Hub",summary:"A Power BI reporting system that preserved historical performance across a platform transition.",tools:"Power BI · SharePoint · Data Modeling",tone:"coffee",image:"/images/digital-marketing-performance-dashboard.png",alt:"Power BI dashboard showing randomized social media and website performance data",featured:true},
 {slug:"asana-marketing-operations",n:"03",type:"Systems & Operations",title:"Marketing Operations System",summary:"An Asana system connecting marketing priorities, workflows, and reporting across the team.",tools:"Asana · Workflow Design · Automation",tone:"blue",image:"/images/asana-marketing-board.png",alt:"Asana marketing project view with custom fields and status tracking",featured:true},
 {slug:"max-verstappen-performance-analysis",n:"04",type:"Personal Explorations",title:"Max Verstappen Performance Analysis",summary:"A first Power BI project exploring season trends, teammate gaps, and competitive performance through Formula 1 data.",tools:"Power BI · Sports Analytics · Data Storytelling",tone:"blue",image:"/images/max-verstappen-performance-dashboard.png",alt:"Power BI dashboard analyzing Max Verstappen season and teammate performance",featured:false},
 {slug:"quality-content-series",n:"05",type:"Marketing & Content",title:"Quality Is a Mindset",summary:"Technical construction content shaped around practical field conditions and quality planning.",tools:"Technical Writing · SEO · Research",tone:"coffee",image:"/images/quality-weather-planning.png",alt:"Steel erection underway on a Carroll Daniel construction site"},
 {slug:"marketing-analytics-reporting-suite",n:"06",type:"Analytics & BI",title:"Marketing Analytics Reporting Suite",summary:"A connected collection of Power BI dashboards for campaign, subsidiary, and executive marketing reporting.",tools:"Power BI · Marketing Analytics · KPI Reporting",tone:"blue",image:"/images/marketing-analytics-reporting-suite.png",alt:"Power BI dashboard showing sample cross-channel campaign performance data"}
];
export function WorkExplorer(){const [filter,setFilter]=useState("All Work");const filters=["All Work","Analytics & BI","Systems & Operations","Marketing & Content","Personal Explorations"];const visible=filter==="All Work"?items:items.filter(i=>i.type===filter);const selectFilter=(nextFilter:string)=>{if(nextFilter===filter)return;const visibleProjectCount=nextFilter==="All Work"?items.length:items.filter(i=>i.type===nextFilter).length;trackEvent("project_filter",{selected_filter:nextFilter,previous_filter:filter,visible_project_count:visibleProjectCount});setFilter(nextFilter)};return <section className="explorer wrap"><div className="filters" aria-label="Filter work">{filters.map(f=><button key={f} className={f===filter?"active":""} onClick={()=>selectFilter(f)}>{f}</button>)}</div><p className="result-count">{visible.length.toString().padStart(2,"0")} ITEM{visible.length===1?"":"S"}</p><div className="work-grid">{visible.map(x=><Link className={`work-card ${x.tone}`} href={`/projects/${x.slug}`} key={x.slug}><div className="work-visual work-photo"><img src={x.image} alt={x.alt}/><span>{x.n}</span></div><small>{x.type}</small><h2>{x.title}</h2><p>{x.summary}</p><div className="card-bottom"><span>{x.tools}</span><b><ArrowUpRight size={18}/></b></div></Link>)}</div></section>}
